services:
  app:
    build: .
    container_name: reservation_system_app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=development
    depends_on:
      - redis
    volumes:
      - ./src:/usr/app/src:z
    command: npm run start

  redis:
    image: redis:7.4.0
    container_name: redis
    ports:
      - "6379:6379"
volumes:
  mongo-data:
